In [2]:
#Data Frames1
#Python is case sensitive
import pandas as pd
titanic_train = pd.read_csv('C:/Users/KARTDH/Desktop/DS/GV-S/titanic/train.csv')
print(type(titanic_train))

<class 'pandas.core.frame.DataFrame'>


In [3]:
#explore the dataframe
titanic_train.shape #No of rows and Column
titanic_train.info() #Data Type and nullable/non-nullable
titanic_train.describe() #Gives statistical information


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [11]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [13]:
titanic_train.dtypes=="object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [14]:
titanic_train.dtypes[titanic_train.dtypes=='object'].index


Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [19]:
#Only interger columns
a=titanic_train.dtypes[titanic_train.dtypes=='int64'].index
titanic_train[a]

PassengerId  Survived  Pclass  SibSp  Parch
0              1         0       3      1      0
1              2         1       1      1      0
2              3         1       3      0      0
3              4         1       1      1      0
4              5         0       3      0      0
..           ...       ...     ...    ...    ...
886          887         0       2      0      0
887          888         1       1      0      0
888          889         0       3      1      2
889          890         1       1      0      0
890          891         0       3      0      0

[891 rows x 5 columns]

In [22]:
#categorical columns describe
a=titanic_train.dtypes[titanic_train.dtypes=='object'].index
titanic_train[a].describe()

Name   Sex Ticket        Cabin Embarked
count                                891   891    891          204      889
unique                               891     2    681          147        3
top     Najib, Miss. Adele Kiamie "Jane"  male   1601  C23 C25 C27        S
freq                                   1   577      7            4      644

In [31]:
#Accessing the single columns
titanic_train['Name']
type(titanic_train['Name'])


pandas.core.series.Series

In [28]:
#Accessing Multiple columns
titanic_train[['PassengerId','Pclass','Name']]
type(titanic_train[['PassengerId','Pclass','Name']])

pandas.core.frame.DataFrame

In [34]:
sorted(titanic_train['Name'])[5:10:2]

['Adahl, Mr. Mauritz Nils Martin',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Albimona, Mr. Nassef Cassem']

In [35]:
titanic_train['Name'].describe()

count                                  891
unique                                 891
top       Najib, Miss. Adele Kiamie "Jane"
freq                                     1
Name: Name, dtype: object

In [36]:
titanic_train[["Ticket"]][4:10]

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742
9  237736

In [38]:
titanic_train.columns


Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [39]:
#Adding new columns
titanic_train["Test"]=0

In [42]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Test  
0      0         A/5 21171   7.2500   NaN        S     0  
1      0          PC 17599  71.2833   C85        C     0  
2      0  STON/O2. 3101282   7.9250   NaN        S     0  
3      0            113803  53.1000  C123        S     0  
4      0            373450   8.0500   NaN        S     0

In [49]:
new_Pclass=pd.Categorical(titanic_train["Pclass"])


In [50]:
new_Pclass=new_Pclass.rename_categories(["C1","C2","C3"])

new_Pclass

[C3, C1, C3, C1, C3, ..., C2, C1, C3, C1, C3]
Length: 891
Categories (3, object): [C1, C2, C3]

In [52]:
#Unique Values
titanic_train["Pclass"].unique()

array([3, 1, 2], dtype=int64)

In [54]:
titanic_train["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [59]:
titanic_train['Age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [60]:
import  numpy as np
np.where (titanic_train['Age'].isnull()==True)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [62]:
#Accessing the Maximum of Fare value
np.where (titanic_train['Fare']== max(titanic_train['Fare']))

(array([258, 679, 737], dtype=int64),)

In [64]:
titanic_train.iloc[np.where (titanic_train['Fare']== max(titanic_train['Fare']))]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  \
258  female  35.0      0      0  PC 17755  512.3292          NaN        C   
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C   
737    male  35.0      0      0  PC 17755  512.3292         B101        C   

     Test  
258     0  
679     0  
737     0

In [66]:

#access both rows and columns of a dataframe
titanic_train.iloc[10:15]

PassengerId  Survived  Pclass                                  Name  \
10           11         1       3       Sandstrom, Miss. Marguerite Rut   
11           12         1       1              Bonnell, Miss. Elizabeth   
12           13         0       3        Saundercock, Mr. William Henry   
13           14         0       3           Andersson, Mr. Anders Johan   
14           15         0       3  Vestrom, Miss. Hulda Amanda Adolfina   

       Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked  Test  
10  female   4.0      1      1    PP 9549  16.7000    G6        S     0  
11  female  58.0      0      0     113783  26.5500  C103        S     0  
12    male  20.0      0      0  A/5. 2151   8.0500   NaN        S     0  
13    male  39.0      1      5     347082  31.2750   NaN        S     0  
14  female  14.0      0      0     350406   7.8542   NaN        S     0

In [70]:
#If you wanted to access by column name then use .loc
titanic_train.loc[10:20,('Name', 'Age')]

Name   Age
10                    Sandstrom, Miss. Marguerite Rut   4.0
11                           Bonnell, Miss. Elizabeth  58.0
12                     Saundercock, Mr. William Henry  20.0
13                        Andersson, Mr. Anders Johan  39.0
14               Vestrom, Miss. Hulda Amanda Adolfina  14.0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0
16                               Rice, Master. Eugene   2.0
17                       Williams, Mr. Charles Eugene   NaN
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0
19                            Masselmani, Mrs. Fatima   NaN
20                               Fynney, Mr. Joseph J  35.0

In [73]:
#conditional access of dataframe
titanic_train.loc[titanic_train.Sex == 'female', 'Fare']

1      71.2833
2       7.9250
3      53.1000
8      11.1333
9      30.0708
        ...   
880    26.0000
882    10.5167
885    29.1250
887    30.0000
888    23.4500
Name: Fare, Length: 314, dtype: float64

In [75]:
#grouping data in data frames
titanic_train.groupby(['Embarked']).size()

Embarked
C    168
Q     77
S    644
dtype: int64

In [76]:
titanic_train.groupby(['Pclass', 'Sex']).size()

Pclass  Sex   
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
dtype: int64

In [77]:
titanic_train.groupby(['Pclass', 'Embarked']).mean()

PassengerId  Survived        Age     SibSp     Parch  \
Pclass Embarked                                                         
1      C          440.800000  0.694118  38.027027  0.376471  0.317647   
       Q          329.500000  0.500000  38.500000  1.500000  0.000000   
       S          477.842520  0.582677  38.152037  0.433071  0.393701   
2      C          444.352941  0.529412  22.766667  0.588235  0.529412   
       Q          418.000000  0.666667  43.500000  0.000000  0.000000   
       S          446.634146  0.463415  30.386731  0.390244  0.371951   
3      C          451.484848  0.378788  20.741951  0.348485  0.378788   
       Q          420.347222  0.375000  25.937500  0.416667  0.180556   
       S          440.685552  0.189802  25.696552  0.705382  0.439093   

                       Fare  Test  
Pclass Embarked                    
1      C         104.718529   0.0  
       Q          90.000000   0.0  
       S          70.364862   0.0  
2      C          25.358335   0.0  
       Q          12.350000   0.0  
       S          20.327439   0.0  
3      C          11.214083   0.0  
       Q          11.183393   0.0  
       S          14.644083   0.0

In [78]:
titanic_train.groupby(['Pclass', 'Embarked', 'Sex']).mean()['Fare']

Pclass  Embarked  Sex   
1       C         female    115.640309
                  male       93.536707
        Q         female     90.000000
                  male       90.000000
        S         female     99.026910
                  male       52.949947
2       C         female     25.268457
                  male       25.421250
        Q         female     12.350000
                  male       12.350000
        S         female     21.912687
                  male       19.232474
3       C         female     14.694926
                  male        9.352237
        Q         female     10.307833
                  male       11.924251
        S         female     18.670077
                  male       13.307149
Name: Fare, dtype: float64